name: "Devenv"

on:
  push:

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Devenv info (needed until release of next version)
        run: devenv info
      - name: Devenv pre-commit
        shell: devenv shell bash -- -e {0}
        run: |
          devenv tasks run bun:install
          devenv tasks run devenv:pre-commit:install
          devenv tasks run devenv:pre-commit:run
      - name: Devenv  test
        run: devenv test
